module1(task1-5 ready temp)
js-tasks-ru/jsbasic-20210225_halen54001 pull request #2
Opened 2021-03-02 11:57 UTC by Destors

2021-03-02 11:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-02 20:07 UTC, SinimaWath requested changes

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return step;
Название переменной не говорящее, другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

`step` - явно ничего не говорит про factorial.

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  for (let i = 2; i <= n; i++) step = step * i;
Однострочная форма записи, не самая читаемая. Более предпочтительно:
```
for () {
  ...
}
```

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  } else return false;
Можно обойтись без регулярки и лучше нужно. Почему:
- Регулярки всегда сложнее поддерживать
- Регулярки сложно читать.
- Регулярки нужно не забывать предкомпилировать. 

Переделай на includes, более понятный и подходящий метод

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  if (!!name && name.length >= 4 && !/\s/g.test(name)) {
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name === null ....`

Это как раз тот случай

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } else return false;
По заданию, функция должна проверять, что в строке есть заданная подстрака, без учета регистра:
`Напишите функцию checkSpam(str), возвращающую true, если str содержит '1xBet' или 'XXX', а иначе false.`

Твое решение свалиться на других любых примерах: `checkSpam('1xBeT')`, `checkSpam('asd 1xBeT asd')`

Подумай и реализуй более универсальное решение

2021-03-02 20:07 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  } else return str;
В этом участке кода else явно лишний. И лишь усложняет понимае кода.

Если if -> true, то в нем есть сразу return, и необходимость в else отпадает

Так будет правильней
```
if (str.length > maxlength) {
    return str.slice(0, maxlength - 1) + "…";
}

return str;
```

Такой код проще понимать

2021-03-03 10:22 UTC, Destors commented on 1-module/5-task/index.js
> +  } else return str;
готово

2021-03-03 10:22 UTC, Destors commented on 1-module/4-task/index.js
> +  } else return false;
готово, использовал метод match

2021-03-03 10:23 UTC, Destors commented on 1-module/2-task/index.js
> +  if (!!name && name.length >= 4 && !/\s/g.test(name)) {
готово

2021-03-03 10:23 UTC, Destors commented on 1-module/2-task/index.js
> +  } else return false;
готово

2021-03-03 10:23 UTC, Destors commented on 1-module/1-task/index.js
> +  for (let i = 2; i <= n; i++) step = step * i;
готово

2021-03-03 10:25 UTC, Destors commented on 1-module/1-task/index.js
> +  return step;
Мне пока сложно работать с циклами и я не до конца понимаю суть факториала. Сделал функцию по тутору для факториалов, название поменял, но насколько это правильно - не уверен.

2021-03-03 19:25 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } else return false;
В условии не сказано, про `free`, и про `now`. А только про `1XbeT` и `xxx`. Поэтому задачу нужно решить, только исходя из этих данных. 

free, now - используется только в наших тестах. И завязываться на них не стоит

Также match, не самый подходящий метод. Потому что он НЕ возвращает true/false. 

Для целей проверки, на соответствие нужен метод test, у регулярных выражений.

2021-03-03 19:26 UTC, SinimaWath requested changes

2021-03-03 19:26 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } else return false;
Также условие можно тоже написать в одну строку

2021-03-03 20:43 UTC, Destors commented on 1-module/4-task/index.js
> +  } else return false;
переделал на test и упростил.

2021-03-04 08:45 UTC, SinimaWath approved these changes

2021-03-04 08:45 UTC, merged