3 module ready
js-tasks-ru/jsbasic-20210225_halen54001 pull request #4
Opened 2021-03-20 10:40 UTC by Destors

2021-03-20 10:40 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-20 14:06 UTC, SinimaWath requested changes

2021-03-20 14:06 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Функция коллбек в методе filter, должна возвращать boolean. В твоем случае это обьект(person) или undefined.

Это очень багоемкое место, так как тут есть неявное приведение типов и это всегда может привести к ошибкам.

Давай перепишем функцию так, чтобы она возвращала: true/false

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#syntax

2021-03-20 14:06 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Стрелочная функция тут тоже будет лаконичней: `() => ....`

2021-03-20 14:06 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map((item) => item.name);
Давай для практики заиспользуем деструкторизацию в аргументе функции-колбек. Это очень частая практика, к которой стоит привыкнуть

https://learn.javascript.ru/destructuring-assignment#umnye-parametry-funktsiy

2021-03-20 14:06 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return result;
Немного непонятно зачем создаешь временный обьект result. В этом случае можно сразу вернуть обьект, без инициализации в переменную:
```

return {
  min ....
  max ....
}

```

2021-03-20 14:06 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  let onlyNumbers = inputArray.filter(Number);
Наверное одно из самых коротких и лаконичных решений которые я видел

2021-03-23 18:39 UTC, SinimaWath approved these changes
Все ок!

2021-03-23 18:40 UTC, merged